//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class BloodBankStockTable
    {
        public int BloodBankStockID { get; set; }
        public int BloodBankID { get; set; }
        public int BloodGroupID { get; set; }
        public int Quantity { get; set; }
        public bool Status { get; set; }
        public string Description { get; set; }
    
        public virtual BloodBankTable BloodBankTable { get; set; }
        public virtual BloodGroupTable BloodGroupTable { get; set; }
    }
}
