//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class RequestTable
    {
        public int RequestID { get; set; }
        public System.DateTime RequestDate { get; set; }
        public int SeekerID { get; set; }
        public int HospitalID { get; set; }
        public int BloodBankID { get; set; }
        public int DonorID { get; set; }
        public int RequiredBloodGroupID { get; set; }
        public int RequestTypeID { get; set; }
        public int RequestByID { get; set; }
        public int AcceptedID { get; set; }
        public int AcceptedTypeID { get; set; }
        public int RequestStatusID { get; set; }
        public System.DateTime ExpectedDate { get; set; }
        public string RequestDetails { get; set; }
    
        public virtual RequestTypeTable RequestTypeTable { get; set; }
        public virtual AcceptedTypeTable AcceptedTypeTable { get; set; }
        public virtual DonorTable DonorTable { get; set; }
        public virtual RequestStatusTable RequestStatusTable { get; set; }
    }
}
