//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class SeekerTable
    {
        public int SeekerID { get; set; }
        public string FullName { get; set; }
        public int Age { get; set; }
        public int CityID { get; set; }
        public int BloodGroupID { get; set; }
        public string ContactNo { get; set; }
        public string CNIC { get; set; }
        public int GenderID { get; set; }
        public int UserID { get; set; }
        public System.DateTime RegistrationDate { get; set; }
    
        public virtual BloodGroupTable BloodGroupTable { get; set; }
        public virtual CityTable CityTable { get; set; }
        public virtual UserTable UserTable { get; set; }
        public virtual GenderTable GenderTable { get; set; }
    }
}
